# fly.toml app configuration file generated for ez-theme-builder on 2024-01-20T10:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "ez-theme-builder"
primary_region = "hkg"

[build]

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
