services:
  - type: web
    name: ez-theme-builder
    env: node
    plan: free
    buildCommand: |
      npm install
      cd frontend && npm install && npm run build
      cd .. && npm run prepare-base
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
