name: Build EZ Theme

on:
  schedule:
    # 每天凌晨2点检查主题仓库更新
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      panel_type:
        description: 'Panel Type'
        required: true
        default: 'Xiao-V2board'
        type: choice
        options:
        - Xiao-V2board
        - V2board
        - SSPanel
      site_name:
        description: 'Site Name'
        required: true
        default: 'EZ Theme'
        type: string
      site_description:
        description: 'Site Description'
        required: false
        default: '专业的主题生成服务'
        type: string
      api_url:
        description: 'API URL'
        required: true
        default: 'https://your-panel.com'
        type: string
      force_rebuild:
        description: 'Force rebuild public theme'
        required: false
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  build-public-theme:
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_rebuild == 'true')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Clone theme repository
      run: |
        echo "Cloning theme repository..."
        # 从实际的主题仓库拉取源码
        git clone https://github.com/wxfyes/EZ-Theme.git theme-source
        cd theme-source
        
        # 显示当前分支和最新提交
        git log --oneline -5
        echo "Theme repository cloned successfully"
        
    - name: Build theme
      run: |
        cd theme-source
        echo "Installing dependencies..."
        npm install
        
        echo "Building theme..."
        npm run build
        
        echo "Build completed. Checking dist directory..."
        ls -la dist/
        
    - name: Create public theme directory
      run: |
        echo "Creating public theme directory..."
        mkdir -p ../public-theme
        
        # 复制构建好的文件
        cp -r theme-source/dist/* ../public-theme/
        
        # 创建配置文件目录
        mkdir -p ../public-theme/config
        
        echo "Public theme directory created successfully"
        ls -la ../public-theme/
        
    - name: Commit public theme
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public-theme/
        git commit -m "Update public theme from external repository - $(date)" || echo "No changes to commit"
        git push origin main

  package-user-theme:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Package user theme
      run: |
        echo "Packaging user theme..."
        
        # 检查公共主题是否存在
        if [ ! -d "public-theme" ]; then
          echo "Public theme not found. Please build public theme first."
          exit 1
        fi
        
        # 创建用户主题目录
        mkdir -p user-theme
        cp -r public-theme/* user-theme/
        
        # 替换配置文件
        cat > user-theme/config/index.js << 'EOF'
        /**
         * 用户主题配置文件
         * 由EZ-Theme构建器自动生成
         */
        export const config = {
            // 面板类型配置
            PANEL_TYPE: '${{ github.event.inputs.panel_type || 'Xiao-V2board' }}',
            
            // API配置
            API_CONFIG: {
                urlMode: 'static',
                staticBaseUrl: ['${{ github.event.inputs.api_url || 'https://your-panel.com' }}/api/v1'],
                autoConfig: {
                    useSameProtocol: true,
                    appendApiPath: true,
                    apiPath: '/api/v1'
                }
            },
            
            // 网站配置
            SITE_CONFIG: {
                siteName: '${{ github.event.inputs.site_name || 'EZ Theme' }}',
                siteDescription: '${{ github.event.inputs.site_description || '专业的主题生成服务' }}',
                copyright: `© ${new Date().getFullYear()} EZ THEME. All Rights Reserved.`,
                showLogo: true,
                landingText: {
                    'zh-CN': '探索全球网络无限可能',
                    'en-US': 'Explore Unlimited Possibilities of Global Network'
                },
                customLandingPage: ''
            },
            
            // 默认配置
            DEFAULT_CONFIG: {
                defaultLanguage: 'zh-CN',
                defaultTheme: 'light',
                primaryColor: '#355cc2',
                enableLandingPage: true
            },
            
            // 认证配置
            AUTH_CONFIG: {
                autoAgreeTerms: true,
                verificationCode: {
                    showCheckSpamTip: true,
                    checkSpamTipDelay: 1000
                },
                popup: {
                    enabled: false,
                    title: "用户须知",
                    content: "<p><strong>欢迎使用我们的服务！</strong></p>",
                    cooldownHours: 0,
                    closeWaitSeconds: 3
                }
            },
            
            // 客户端下载配置
            CLIENT_CONFIG: {
                showDownloadCard: true,
                showIOS: true,
                showAndroid: true,
                showMacOS: true,
                showWindows: true,
                showLinux: true,
                showOpenWrt: false,
                clientLinks: {
                    ios: 'https://apps.apple.com/app/xxx',
                    android: 'https://play.google.com/store/apps/xxx',
                    macos: 'https://github.com/xxx/releases/latest',
                    windows: 'https://github.com/xxx/releases/latest',
                    linux: 'https://github.com/xxx/releases/latest',
                    openwrt: 'https://github.com/xxx/releases/latest'
                },
                showShadowrocket: true,
                showSurge: true,
                showStash: true,
                showQuantumultX: true,
                showHiddifyIOS: true,
                showSingboxIOS: true,
                showLoon: true,
                showFlClashAndroid: true,
                showV2rayNG: true,
                showClashAndroid: true,
                showSurfboard: true,
                showClashMetaAndroid: true,
                showNekobox: true,
                showSingboxAndroid: true,
                showHiddifyAndroid: true,
                showFlClashWindows: true,
                showClashVergeWindows: true,
                showClashWindows: true,
                showNekoray: true,
                showSingboxWindows: true,
                showHiddifyWindows: true,
                showFlClashMac: true,
                showClashVergeMac: true,
                showClashX: true,
                showClashMetaX: true,
                showSurgeMac: true,
                showStashMac: true,
                showQuantumultXMac: true,
                showSingboxMac: true,
                showHiddifyMac: true
            },
            
            // 其他配置
            API_MIDDLEWARE_ENABLED: false,
            SILENT_API_CHECK: true,
            API_CHECK_TIMEOUT: 3000,
            API_CHECK_CACHE_ENABLED: true,
            API_CHECK_CACHE_DURATION: 300000,
            API_MIDDLEWARE_URL: '',
            API_MIDDLEWARE_PATH: '/ez/ez',
            
            // 仪表板配置
            DASHBOARD_CONFIG: {
                showUserEmail: false,
                importButtonHighlightBtnbgcolor: false,
                enableResetTraffic: true,
                resetTrafficDisplayMode: 'low',
                lowTrafficThreshold: 10,
                enableRenewPlan: true,
                renewPlanDisplayMode: 'always',
                expiringThreshold: 7,
                showOnlineDevicesLimit: true,
                showImportSubscription: true
            },
            
            // 商店配置
            SHOP_CONFIG: {
                showHotSaleBadge: false,
                showPlanFeatureCards: true,
                autoSelectMaxPeriod: false,
                hidePeriodTabs: false,
                lowStockThreshold: 5,
                enableDiscountCalculation: true,
                periodOrder: [
                    'three_year_price',
                    'two_year_price',
                    'year_price',
                    'half_year_price',
                    'quarter_price',
                    'month_price',
                    'onetime_price'
                ],
                popup: {
                    enabled: true,
                    title: "用户须知",
                    content: "<p><strong>常规套餐默认每月订单日重置流量，您当月未用使用完的流量，不会累积到下个月</strong></p>",
                    cooldownHours: 0,
                    closeWaitSeconds: 0
                }
            },
            
            // 订单配置
            ORDER_CONFIG: {
                confirmOrder: true,
                confirmOrderContent: "<p><strong style='color: red'>无法提供相关教程和使用说明。</strong></p><p><strong style='color: red'>不会使用请勿购买，没有退款政策</strong></p>"
            },
            
            // 用户配置
            PROFILE_CONFIG: {
                showGiftCardRedeem: false,
                showRecentDevices: true
            },
            
            // 安全配置
            SECURITY_CONFIG: {
                enableFrontendDomainCheck: false
            },
            
            AUTHORIZED_DOMAINS: [
                "test.eztheme.test",
                "test1.eztheme.test"
            ],
            
            // 验证码配置
            CAPTCHA_CONFIG: {
                captchaType: 'google',
                google: {
                    verifyUrl: 'https://www.google.com/recaptcha/api/siteverify'
                },
                cloudflare: {
                    verifyUrl: 'https://challenges.cloudflare.com/turnstile/v0/siteverify'
                }
            },
            
            // 自定义标头
            CUSTOM_HEADERS: {
                enabled: false,
                headers: {}
            },
            
            // 支付配置
            PAYMENT_CONFIG: {
                openPaymentInNewTab: true,
                qrcodeSize: 200,
                qrcodeColor: '#000000',
                qrcodeBackground: '#ffffff',
                autoCheckPayment: true,
                autoCheckInterval: 5000,
                autoCheckMaxTimes: 60,
                useSafariPaymentModal: true,
                autoSelectFirstMethod: true
            },
            
            // 钱包配置
            WALLET_CONFIG: {
                presetAmounts: [6, 30, 68, 128, 256, 328, 648, 1280],
                defaultSelectedAmount: null,
                minimumDepositAmount: 1
            },
            
            // 邀请配置
            INVITE_CONFIG: {
                showCommissionBadge: false,
                recordsPerPage: 10,
                inviteLinkConfig: {
                    linkMode: 'auto',
                    customDomain: 'https://example.com'
                }
            },
            
            // 浏览器限制
            BROWSER_RESTRICT_CONFIG: {
                enabled: true,
                restrictBrowsers: {
                    '360': true,
                    'QQ': true,
                    'WeChat': true,
                    'Baidu': true,
                    'Sogou': true,
                    'UC': false,
                    'Maxthon': false
                },
                recommendedBrowsers: {
                    'Chrome': 'https://www.google.cn/chrome/',
                    'Edge': 'https://www.microsoft.com/edge'
                }
            },
            
            // 工单配置
            TICKET_CONFIG: {
                includeUserInfoInTicket: true,
                popup: {
                    enabled: true,
                    title: "工单须知",
                    content: "<p>请您准确描述您的问题，再提交工单，以便我们更快帮助您。</p>",
                    cooldownHours: 24,
                    closeWaitSeconds: 0
                }
            },
            
            // 流量明细
            TRAFFICLOG_CONFIG: {
                enableTrafficLog: true,
                daysToShow: 30
            },
            
            // 节点配置
            NODES_CONFIG: {
                showNodeRate: true,
                showNodeDetails: false,
                allowViewNodeInfo: true
            },
            
            // 客服配置
            CUSTOMER_SERVICE_CONFIG: {
                enabled: false,
                type: 'crisp',
                customHtml: '',
                embedMode: 'embed',
                showWhenNotLoggedIn: true,
                iconPosition: {
                    desktop: {
                        left: '20px',
                        bottom: '20px'
                    },
                    mobile: {
                        right: '20px',
                        bottom: '100px'
                    }
                }
            },
            
            // More页面配置
            MORE_PAGE_CONFIG: {
                enableCustomCards: false,
                customCards: [
                    {
                        id: 'github',
                        title: 'GitHub',
                        description: '访问我们的GitHub',
                        svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-github" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5" /></svg>',
                        url: 'https://github.com',
                        openInNewTab: true
                    },
                    {
                        id: 'telegram',
                        title: 'Telegram',
                        description: '加入我们的Telegram频道',
                        svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-telegram" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M15 10l-4 4l6 6l4 -16l-18 7l4 2l2 6l3 -4" /></svg>',
                        url: 'https://t.me/your_group',
                        openInNewTab: true
                    }
                ]
            }
        };
        
        window.EZ_CONFIG = config;
        EOF
        
        # 创建 README 文件
        cat > user-theme/README.md << 'EOF'
        # EZ Theme 用户主题包

        ## 构建信息
        - **构建时间**: $(date)
        - **构建版本**: v${{ github.run_number }}
        - **面板类型**: ${{ github.event.inputs.panel_type || 'Xiao-V2board' }}
        - **网站名称**: ${{ github.event.inputs.site_name || 'EZ Theme' }}
        - **API地址**: ${{ github.event.inputs.api_url || 'https://your-panel.com' }}

        ## 使用方法
        1. 下载 ZIP 文件
        2. 解压到你的网站根目录
        3. 确保 `index.html` 在网站根目录
        4. 配置文件已自动生成，无需手动配置

        ## 文件结构
        ```
        user-theme/
        ├── index.html          # 主页面
        ├── config/
        │   └── index.js        # 配置文件（已配置）
        ├── assets/             # 静态资源
        └── README.md           # 说明文件
        ```

        ## 注意事项
        - 配置文件已根据您的设置自动生成
        - 如需修改配置，请编辑 `config/index.js` 文件
        - 确保您的面板 API 地址正确
        EOF
        
        echo "User theme packaged successfully"
        
    - name: Create ZIP file
      run: |
        cd user-theme
        zip -r ../user-theme-build.zip .
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: user-theme-build
        path: user-theme-build.zip
        
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: user-theme-build.zip
        tag_name: user-theme-v${{ github.run_number }}
        name: User Theme Build v${{ github.run_number }}
        body: |
          ## EZ Theme 用户主题包
          
          **面板类型:** ${{ github.event.inputs.panel_type || 'Xiao-V2board' }}
          **网站名称:** ${{ github.event.inputs.site_name || 'EZ Theme' }}
          **API地址:** ${{ github.event.inputs.api_url || 'https://your-panel.com' }}
          
          ### 使用方法
          1. 下载 ZIP 文件
          2. 解压到你的网站根目录
          3. 配置文件已自动生成，无需手动配置
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
